In [14]:
# Import dependencies
import pandas as pd

# Read in Raw Data

In [15]:
# Import csv data into a dataframe
beer_df = pd.read_csv("../Resources/beer_reviews.csv")
beer_df.head()

,index,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

# Drop Null Values

In [16]:
#Checking for null values
beer_df.isnull().sum()

index                     0
brewery_id                0
brewery_name             15
review_time               0
review_overall            0
review_aroma              0
review_appearance         0
review_profilename      348
beer_style                0
review_palate             0
review_taste              0
beer_name                 0
beer_abv              67785
beer_beerid               0
dtype: int64

In [17]:
#Dropping null values
beer_df.dropna(inplace=True)

In [18]:
beer_df.head()

,index,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

# Unix to Date + Time

In [19]:
# Convert the unix timestamp to datetime
beer_df['review_time'] = pd.to_datetime(beer_df['review_time'], unit='s')

In [20]:
# Format the datetime as a string
beer_df['review_time'] = beer_df['review_time'].dt.strftime('%m/%d/%Y %I:%M%p')

In [21]:
beer_df.head()

,index,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,0,10325,Vecchio Birraio,02/16/2009 08:57PM,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,1,10325,Vecchio Birraio,03/01/2009 01:44PM,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,2,10325,Vecchio Birraio,03/01/2009 02:10PM,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,3,10325,Vecchio Birraio,02/15/2009 07:12PM,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,4,1075,Caldera Brewing Company,12/30/2010 06:53PM,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

# Rename Headers

In [22]:
beer_df = beer_df.rename(columns={'brewery_id': 'Brewery ID', 'review_time': 'Review Time', 'review_overall': 'Overal Review', 'review_aroma': 'Aroma Review', 'review_appearance': 'Appearance Review', 'review_profilename': 'Reviewer Name', 'beer_style': 'Beer Style', 'review palate': 'Palate Review', 'review_taste': 'Taste Review', 'beer_name': 'Beer Name', 'beer_abv': 'ABV', 'beer_beerid': 'Beer ID', 
                      'brewery_name': 'Brewery Name'})

In [23]:
beer_df.columns

Index(['index', 'Brewery ID', 'Brewery Name', 'Review Time', 'Overal Review',
       'Aroma Review', 'Appearance Review', 'Reviewer Name', 'Beer Style',
       'review_palate', 'Taste Review', 'Beer Name', 'ABV', 'Beer ID'],
      dtype='object')

In [24]:
beer_df.head()

,index,Brewery ID,Brewery Name,Review Time,Overal Review,Aroma Review,Appearance Review,Reviewer Name,Beer Style,review_palate,Taste Review,Beer Name,ABV,Beer ID
0,0,10325,Vecchio Birraio,02/16/2009 08:57PM,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,1,10325,Vecchio Birraio,03/01/2009 01:44PM,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,2,10325,Vecchio Birraio,03/01/2009 02:10PM,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,3,10325,Vecchio Birraio,02/15/2009 07:12PM,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,4,1075,Caldera Brewing Company,12/30/2010 06:53PM,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

# Export to CSV

In [12]:
beer_df.to_csv('clean_beer.csv')

# More Information

In [30]:
# Number of Unique Beers
unique_beers = beer_df['Beer Name'].nunique()
unique_beers

44075

In [31]:
# Number of Unique Reviewers
unique_reviewers = beer_df['Reviewer Name'].nunique()
unique_reviewers

32908

In [32]:
# Average Review
review_average = beer_df['Overal Review'].mean()
review_average

3.823937521649968